export const URL_HOME = '/'
export const URL_CREATE_TODO = '/create-todo'
export const URL_TODO_LIST = '/todo-list'
export const URL_NOT_FOUND = '/404'
export const URL_REGISTER= '/signup'
export const URL_LOGIN= '/signin'
export const URL_SCHEDULE= '/schedule'
export const URL_CREATE_APPOINTMENT= '/create-appointment'